//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18034
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace sixpetals.TextileToHtml {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("sixpetals.TextileToHtml.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   This generator only supports &apos;Constant&apos; and &apos;Variable&apos; child nodes for a &apos;Class&apos; node. Found: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BadClassMemberName {
            get {
                return ResourceManager.GetString("BadClassMemberName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   For types, the access attribute must be &apos;public&apos; or &apos;internal&apos;. Found: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BadTypeAccess {
            get {
                return ResourceManager.GetString("BadTypeAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   For &apos;Variable&apos; nodes, the &apos;access&apos; attribute must be &apos;public&apos;, &apos;protected&apos;, or &apos;private&apos;. Found: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BadVariableAccess {
            get {
                return ResourceManager.GetString("BadVariableAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;Constant&apos; and &apos;Variable&apos; child nodes of a &apos;Class&apos; node must have a &apos;name&apos; attribute に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ClassMemberNoName {
            get {
                return ResourceManager.GetString("ClassMemberNoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;Constant&apos; and &apos;Variable&apos; child nodes of a &apos;Class&apos; node must have a &apos;type&apos; attribute に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ClassMemberNoType {
            get {
                return ResourceManager.GetString("ClassMemberNoType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Each &apos;Class&apos; node must have a name attribute に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ClassNodeNoName {
            get {
                return ResourceManager.GetString("ClassNodeNoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;Constant&apos; nodes must have a &apos;value&apos; attribute に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConstantNoValue {
            get {
                return ResourceManager.GetString("ConstantNoValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;Enum&apos; nodes can only have &apos;EnumMember&apos; child nodes. Found: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EnumInvalidChild {
            get {
                return ResourceManager.GetString("EnumInvalidChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Each &apos;EnumMember&apos; node must have a name attribute に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EnumMemberNodeNoName {
            get {
                return ResourceManager.GetString("EnumMemberNodeNoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If &apos;Enum&apos; node has flagsAttribute=&quot;true&quot;, each &apos;EnumMember&apos; child must have a value attribute に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EnumMemberValueMissing {
            get {
                return ResourceManager.GetString("EnumMemberValueMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Each &apos;Enum&apos; node must have a name attribute に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EnumNodeNoName {
            get {
                return ResourceManager.GetString("EnumNodeNoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;Enum&apos; nodes must have at least one &apos;EnumMember&apos; child node に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EnumNoMembers {
            get {
                return ResourceManager.GetString("EnumNoMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The call to GetDefaultExtension() has failed due to the exception: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GetDefaultExtensionFailed {
            get {
                return ResourceManager.GetString("GetDefaultExtensionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Expected root element: &apos;Types&apos;. Found: {0}   に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidRoot {
            get {
                return ResourceManager.GetString("InvalidRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The &apos;Types&apos; root node should only contain &apos;Class&apos; or &apos;Enum&apos; child nodes. Found: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidType {
            get {
                return ResourceManager.GetString("InvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The &apos;Types&apos; root element must contain at least one &apos;Class&apos; or &apos;Enum&apos; child に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NoTypes {
            get {
                return ResourceManager.GetString("NoTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;Constant&apos; nodes can not have the &apos;static&apos; attribute に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StaticConstant {
            get {
                return ResourceManager.GetString("StaticConstant", resourceCulture);
            }
        }
    }
}
